package org.nmeict.smvdu.Beans;
// Generated Apr 5, 2013 9:02:16 PM by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.component.UIData;
import javax.faces.model.SelectItem;

import org.nmeict.smvdu.Beans.SpringClassFile.IOrgBranchService;
import org.nmeict.smvdu.Beans.SpringClassFile.OrgBranchService;
import org.nmeict.smvdu.HibernateHelper.OrgProfileSessionDetails;

/**
 * BranchMaster generated by hbm2java
 */
@ManagedBean(name="branchMaster")
@RequestScoped
public class BranchMaster  implements java.io.Serializable {


	private Integer bmSeqNo;
    private OrgDepartmentType orgDepartmentType;
    private DegreeType degreeType;
    private OrgProfile orgProfile;
    private String branchName;
    private String bmDegreeCreaterId;
    private String bmDegreeModifierId;
    private Date bmCreaterDate;
    private Date bmModifierDate;
    private Set studentRegMasters = new HashSet(0);
    private Set otherFeeHeadMasters = new HashSet(0);
    private Set studentMasters = new HashSet(0);
     
     private String departmentName;
     private String degreeName;
     private Integer degreeTypeCode;
     private Integer departmentTypeCode;
     private IOrgBranchService iOrgBranchService = new OrgBranchService();
     private UIData dataGrid;
     private List<BranchMaster> listBranchMaster = new ArrayList<BranchMaster>();
     private SelectItem[] items;
     
     
     public BranchMaster() {
     }

     public BranchMaster(OrgDepartmentType orgDepartmentType, DegreeType degreeType, OrgProfile orgProfile, String branchName, String bmDegreeCreaterId, String bmDegreeModifierId, Date bmCreaterDate, Date bmModifierDate, Set studentRegMasters, Set otherFeeHeadMasters, Set studentMasters) {
        this.orgDepartmentType = orgDepartmentType;
        this.degreeType = degreeType;
        this.orgProfile = orgProfile;
        this.branchName = branchName;
        this.bmDegreeCreaterId = bmDegreeCreaterId;
        this.bmDegreeModifierId = bmDegreeModifierId;
        this.bmCreaterDate = bmCreaterDate;
        this.bmModifierDate = bmModifierDate;
        this.studentRegMasters = studentRegMasters;
        this.otherFeeHeadMasters = otherFeeHeadMasters;
        this.studentMasters = studentMasters;
     }
            public Integer getBmSeqNo() {
        return this.bmSeqNo;
    }
    
    public void setBmSeqNo(Integer bmSeqNo) {
        this.bmSeqNo = bmSeqNo;
    }
    public OrgDepartmentType getOrgDepartmentType() {
        return this.orgDepartmentType;
    }
    
    public void setOrgDepartmentType(OrgDepartmentType orgDepartmentType) {
        this.orgDepartmentType = orgDepartmentType;
    }
    public DegreeType getDegreeType() {
        return this.degreeType;
    }
    
    public void setDegreeType(DegreeType degreeType) {
        this.degreeType = degreeType;
    }
    
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public Date getBmCreaterDate() {
        return this.bmCreaterDate;
    }
    
    public void setBmCreaterDate(Date bmCreaterDate) {
        this.bmCreaterDate = bmCreaterDate;
    }
    public Date getBmModifierDate() {
        return this.bmModifierDate;
    }
    
    public void setBmModifierDate(Date bmModifierDate) {
        this.bmModifierDate = bmModifierDate;
    }

	public Integer getDegreeTypeCode() {
		return degreeTypeCode;
	}

	public void setDegreeTypeCode(Integer degreeTypeCode) {
		this.degreeTypeCode = degreeTypeCode;
	}

	public Integer getDepartmentTypeCode() {
		return departmentTypeCode;
	}

	public void setDepartmentTypeCode(Integer departmentTypeCode) {
		this.departmentTypeCode = departmentTypeCode;
	}
	
	
	
	public OrgProfile getOrgProfile() {
		return orgProfile;
	}

	public void setOrgProfile(OrgProfile orgProfile) {
		this.orgProfile = orgProfile;
	}

	public String getBmDegreeCreaterId() {
		return bmDegreeCreaterId;
	}

	public void setBmDegreeCreaterId(String bmDegreeCreaterId) {
		this.bmDegreeCreaterId = bmDegreeCreaterId;
	}

	
	public String getBmDegreeModifierId() {
		return bmDegreeModifierId;
	}

	public Set getStudentMasters() {
		return studentMasters;
	}

	public void setStudentMasters(Set studentMasters) {
		this.studentMasters = studentMasters;
	}

	public void setBmDegreeModifierId(String bmDegreeModifierId) {
		this.bmDegreeModifierId = bmDegreeModifierId;
	}

	public IOrgBranchService getiOrgBranchService() {
		return iOrgBranchService;
	}

	public void setiOrgBranchService(IOrgBranchService iOrgBranchService) {
		this.iOrgBranchService = iOrgBranchService;
	}

	
	
	
	
	public Set getStudentRegMasters() {
		return studentRegMasters;
	}

	public void setStudentRegMasters(Set studentRegMasters) {
		this.studentRegMasters = studentRegMasters;
	}

	public String getDepartmentName() {
		return departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	public String getDegreeName() {
		return degreeName;
	}

	public void setDegreeName(String degreeName) {
		this.degreeName = degreeName;
	}
    
	
	public void saveBranch()
	{
		OrgProfile opByOrgCode = new OrgProfile();
		OrgDepartmentType odt = new OrgDepartmentType();
		DegreeType dt = new DegreeType();
		opByOrgCode.setOrgId(new OrgProfileSessionDetails().getOrgProfileSession().getOrgId());
		odt.setOdtSeqNo(this.getDepartmentTypeCode());
		dt.setSeqNo(this.getDegreeTypeCode());
		this.setBmDegreeCreaterId(new OrgProfileSessionDetails().getOrgProfileSession().getOrgAdminemailid());
		this.setDegreeType(dt);
		this.setBmCreaterDate(new Date());
		this.setOrgDepartmentType(odt);
		this.setOrgProfile(opByOrgCode);
		getiOrgBranchService().addOrgBranch(this);
		
		
	}

	public Set getOtherFeeHeadMasters() {
		return otherFeeHeadMasters;
	}
	public void setOtherFeeHeadMasters(Set otherFeeHeadMasters) {
		this.otherFeeHeadMasters = otherFeeHeadMasters;
	}
	public SelectItem[] getItems() {
		
		List<BranchMaster> branchCode = getiOrgBranchService().loadAllBranchList();
		items = new SelectItem[branchCode.size()];
		for(int i=0;i<branchCode.size();i++)
		{
			BranchMaster dt = branchCode.get(i);
			SelectItem si = new SelectItem(dt.getBmSeqNo(),dt.getBranchName());
			items[i] = si;
		}
		return items;
	}
	public void setItems(SelectItem[] items) {
		this.items = items;
	}
	public UIData getDataGrid() {
		return dataGrid;
	}

	public void setDataGrid(UIData dataGrid) {
		this.dataGrid = dataGrid;
	}

	public List<BranchMaster> getListBranchMaster() {
		listBranchMaster = getiOrgBranchService().loadAllBranchList();
		dataGrid.setValue(listBranchMaster);
		return listBranchMaster;
	}

	public void setListBranchMaster(List<BranchMaster> listBranchMaster) {
		this.listBranchMaster = listBranchMaster;
	}

    public void update()
    {
    	List<BranchMaster> branchMaster = (ArrayList<BranchMaster>) dataGrid.getValue();
    	getiOrgBranchService().update(branchMaster);
    }


}


