package org.nmeict.smvdu.Beans;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
// Generated Mar 30, 2013 9:21:41 AM by Hibernate Tools 3.2.1.GA
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;

import org.nmeict.smvdu.Beans.SpringClassFile.IOrgLoginProfile;
import org.nmeict.smvdu.Beans.SpringClassFile.OrgLoginProfileService;
import org.nmeict.smvdu.HibernateHelper.OrgProfileSessionDetails;


@ManagedBean(name="orgLoginDetails")
@RequestScoped
/**
 * OrgLoginDetails generated by hbm2java
 */
public class OrgLoginDetails  implements java.io.Serializable {


     private String orgId;
     private OrgProfile orgProfile;
     private String adminId;
     private String orgPassword;
     private String id;
     private IOrgLoginProfile iOrgLoginProfile = new OrgLoginProfileService();
    public OrgLoginDetails() {
    	
    }

	
    public OrgLoginDetails(String orgId, OrgProfile orgProfile, String adminId) {
        this.orgId = orgId;
        this.orgProfile = orgProfile;
        this.adminId = adminId;
    }
    public OrgLoginDetails(String orgId, OrgProfile orgProfile, String adminId, String orgPassword) {
       this.orgId = orgId;
       this.orgProfile = orgProfile;
       this.adminId = adminId;
       this.orgPassword = orgPassword;
    }
   
    public String getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(String orgId) {
        this.orgId = orgId;
    }
    public OrgProfile getOrgProfile() {
        return this.orgProfile;
    }
    
    public void setOrgProfile(OrgProfile orgProfile) {
        this.orgProfile = orgProfile;
    }
    public String getAdminId() {
        return this.adminId;
    }
    
    public void setAdminId(String adminId) {
        this.adminId = adminId;
    }
    public String getOrgPassword() {
        return this.orgPassword;
    }
    
    public void setOrgPassword(String orgPassword) {
        this.orgPassword = orgPassword;
    }

    

    public IOrgLoginProfile getiOrgLoginProfile() {
		return iOrgLoginProfile;
	}


	public void setiOrgLoginProfile(IOrgLoginProfile iOrgLoginProfile) {
		this.iOrgLoginProfile = iOrgLoginProfile;
	}


	public String validate()
	{
		try
		{
			String page = null;
			OrgProfile op = new OrgProfile();
			boolean b = getiOrgLoginProfile().validateOrgUser(this);
			if(b == true)
			{
				op = getiOrgLoginProfile().loadAllDetails(this.getOrgId());
				this.setOrgProfile(op);
				FacesContext.getCurrentInstance().getExternalContext().getSessionMap().put("org",this);
				page = "MainPage.xhtml?faces-redirect=true";
			}
			else
			{
				FacesContext.getCurrentInstance().addMessage("", new FacesMessage(FacesMessage.SEVERITY_ERROR, "User/Email ID or Password Ane Not Correct", ""));
			}
			return page;
		}
		catch(Exception ex)
		{
			return null;
		}
	}

}


