package org.nmeict.smvdu.Beans;
// Generated Mar 30, 2013 9:21:41 AM by Hibernate Tools 3.2.1.GA


import java.io.File;
import java.io.FileInputStream;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;

import org.nmeict.smvdu.Beans.SpringClassFile.IOrgProfileService;
import org.nmeict.smvdu.Beans.SpringClassFile.OrgProfileService;
import org.nmeict.smvdu.HibernateHelper.OrgProfileSessionDetails;
@ManagedBean(name="orgProfileBeans")
@SessionScoped
/**
 * OrgProfile generated by hbm2java
 */
public class OrgProfile  implements java.io.Serializable {


	private String orgId;
    private String orgName;
    private String orgCity;
    private Integer orgPincode;
    private String orgState;
    private Integer orgLl;
    private String orgCountrycode;
    private Integer orgRegioncode;
    private String orgInstitutedomain;
    private String orgToi;
    private String orgInstituteweb;
    private String orgAffiliation;
    private String orgAdminfn;
    private String orgAdminln;
    private String orgAdmindesig;
    private String orgAdminemailid;
    private String orgMasterPassword;
    private String orgTagline;
    private String orgEmail;
    private String orgWeb;
    private String orgPhone;
    private String orgAddress1;
    private String orgAddress2;
    private byte[] orgLogo;
    private String orgRecoveryId;
    private String orgTanno;
    private Integer orgRegNoti;
    private Byte orgStatus;
    private Date orgRegDate;
    private String orgCountryName;
    private Set studentFeesMasters = new HashSet(0);
    private Set bankProfiles = new HashSet(0);
    private Set courseGroupMasters = new HashSet(0);
    private Set tempFinalReports = new HashSet(0);
    private Set studentRegMasters = new HashSet(0);
    private Set challanMasters = new HashSet(0);
    private Set modeOfPayments = new HashSet(0);
    private Set mopHeadFieldses = new HashSet(0);
    private Set adminFeeAdminMasters = new HashSet(0);
    private Set examCodeSetUps = new HashSet(0);
    private Set orgLoginDetailses = new HashSet(0);
    private Set studentMasters = new HashSet(0);
    private Set degreeTypes = new HashSet(0);
    private Set branchMasters = new HashSet(0);
    private Set orgDepartmentTypes = new HashSet(0);
    private Set otherFeeHeadMasters = new HashSet(0);
    private Set orgLogoDetailses = new HashSet(0);
    private Set collegePendingStatuses = new HashSet(0);
    private Set semesterMasters = new HashSet(0);
    
    
    private OrgLoginDetails orgLoginDetails = new OrgLoginDetails();
     private OrgLogoDetails orgLogoDetails = new OrgLogoDetails();
     private IOrgProfileService iOrgProfileService = new OrgProfileService();
     private String fileName;
     private String filePath;    
     public OrgProfile() {
     }

 	
     public OrgProfile(String orgId) {
         this.orgId = orgId;
     }
     public OrgProfile(String orgId, String orgName, String orgCity, Integer orgPincode, String orgState, Integer orgLl, String orgCountrycode, Integer orgRegioncode, String orgInstitutedomain, String orgToi, String orgInstituteweb, String orgAffiliation, String orgAdminfn, String orgAdminln, String orgAdmindesig, String orgAdminemailid, String orgMasterPassword, String orgTagline, String orgEmail, String orgWeb, String orgPhone, String orgAddress1, String orgAddress2, byte[] orgLogo, String orgRecoveryId, String orgTanno, Integer orgRegNoti, Byte orgStatus, Date orgRegDate, String orgCountryName, Set studentFeesMasters, Set bankProfiles, Set courseGroupMasters, Set tempFinalReports, Set studentRegMasters, Set challanMasters, Set modeOfPayments, Set mopHeadFieldses, Set adminFeeAdminMasters, Set examCodeSetUps, Set semesterMasters, Set orgLoginDetailses, Set studentMasters, Set degreeTypes, Set branchMasters, Set orgDepartmentTypes, Set otherFeeHeadMasters, Set orgLogoDetailses, Set collegePendingStatuses) {
        this.orgId = orgId;
        this.orgName = orgName;
        this.orgCity = orgCity;
        this.orgPincode = orgPincode;
        this.orgState = orgState;
        this.orgLl = orgLl;
        this.orgCountrycode = orgCountrycode;
        this.orgRegioncode = orgRegioncode;
        this.orgInstitutedomain = orgInstitutedomain;
        this.orgToi = orgToi;
        this.orgInstituteweb = orgInstituteweb;
        this.orgAffiliation = orgAffiliation;
        this.orgAdminfn = orgAdminfn;
        this.orgAdminln = orgAdminln;
        this.orgAdmindesig = orgAdmindesig;
        this.orgAdminemailid = orgAdminemailid;
        this.orgMasterPassword = orgMasterPassword;
        this.orgTagline = orgTagline;
        this.orgEmail = orgEmail;
        this.orgWeb = orgWeb;
        this.orgPhone = orgPhone;
        this.orgAddress1 = orgAddress1;
        this.orgAddress2 = orgAddress2;
        this.orgLogo = orgLogo;
        this.orgRecoveryId = orgRecoveryId;
        this.orgTanno = orgTanno;
        this.orgRegNoti = orgRegNoti;
        this.orgStatus = orgStatus;
        this.orgRegDate = orgRegDate;
        this.orgCountryName = orgCountryName;
        this.studentFeesMasters = studentFeesMasters;
        this.bankProfiles = bankProfiles;
        this.courseGroupMasters = courseGroupMasters;
        this.tempFinalReports = tempFinalReports;
        this.studentRegMasters = studentRegMasters;
        this.challanMasters = challanMasters;
        this.modeOfPayments = modeOfPayments;
        this.mopHeadFieldses = mopHeadFieldses;
        this.adminFeeAdminMasters = adminFeeAdminMasters;
        this.examCodeSetUps = examCodeSetUps;
        this.semesterMasters = semesterMasters;
        this.orgLoginDetailses = orgLoginDetailses;
        this.studentMasters = studentMasters;
        this.degreeTypes = degreeTypes;
        this.branchMasters = branchMasters;
        this.orgDepartmentTypes = orgDepartmentTypes;
        this.otherFeeHeadMasters = otherFeeHeadMasters;
        this.orgLogoDetailses = orgLogoDetailses;
        this.collegePendingStatuses = collegePendingStatuses;
     }
       
     
    public String getOrgId() {
        return this.orgId;
    }
    
    public Set getSemesterMasters() {
		return semesterMasters;
	}


	public void setSemesterMasters(Set semesterMasters) {
		this.semesterMasters = semesterMasters;
	}


	public void setOrgId(String orgId) {
        this.orgId = orgId;
    }
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
    public String getOrgCity() {
        return this.orgCity;
    }
    
    public void setOrgCity(String orgCity) {
        this.orgCity = orgCity;
    }
    public Integer getOrgPincode() {
        return this.orgPincode;
    }
    
    public void setOrgPincode(Integer orgPincode) {
        this.orgPincode = orgPincode;
    }
    public String getOrgState() {
        return this.orgState;
    }
    
    public void setOrgState(String orgState) {
        this.orgState = orgState;
    }
    public Integer getOrgLl() {
        return this.orgLl;
    }
    
    public void setOrgLl(Integer orgLl) {
        this.orgLl = orgLl;
    }
    public String getOrgCountrycode() {
        return this.orgCountrycode;
    }
    
    public void setOrgCountrycode(String orgCountrycode) {
        this.orgCountrycode = orgCountrycode;
    }
    public Integer getOrgRegioncode() {
        return this.orgRegioncode;
    }
    
    public void setOrgRegioncode(Integer orgRegioncode) {
        this.orgRegioncode = orgRegioncode;
    }
    public String getOrgInstitutedomain() {
        return this.orgInstitutedomain;
    }
    
    public void setOrgInstitutedomain(String orgInstitutedomain) {
        this.orgInstitutedomain = orgInstitutedomain;
    }
    public String getOrgToi() {
        return this.orgToi;
    }
    
    public void setOrgToi(String orgToi) {
        this.orgToi = orgToi;
    }
    public String getOrgInstituteweb() {
        return this.orgInstituteweb;
    }
    
    public void setOrgInstituteweb(String orgInstituteweb) {
        this.orgInstituteweb = orgInstituteweb;
    }
    public String getOrgAffiliation() {
        return this.orgAffiliation;
    }
    
    public void setOrgAffiliation(String orgAffiliation) {
        this.orgAffiliation = orgAffiliation;
    }
    public String getOrgAdminfn() {
        return this.orgAdminfn;
    }
    
    public void setOrgAdminfn(String orgAdminfn) {
        this.orgAdminfn = orgAdminfn;
    }
    public String getOrgAdminln() {
        return this.orgAdminln;
    }
    
    public void setOrgAdminln(String orgAdminln) {
        this.orgAdminln = orgAdminln;
    }
    public String getOrgAdmindesig() {
        return this.orgAdmindesig;
    }
    
    public void setOrgAdmindesig(String orgAdmindesig) {
        this.orgAdmindesig = orgAdmindesig;
    }
    public String getOrgAdminemailid() {
        return this.orgAdminemailid;
    }
    
    public void setOrgAdminemailid(String orgAdminemailid) {
        this.orgAdminemailid = orgAdminemailid;
    }
    public String getOrgMasterPassword() {
        return this.orgMasterPassword;
    }
    
    public void setOrgMasterPassword(String orgMasterPassword) {
        this.orgMasterPassword = orgMasterPassword;
    }
    public String getOrgTagline() {
        return this.orgTagline;
    }
    
    public void setOrgTagline(String orgTagline) {
        this.orgTagline = orgTagline;
    }
    public String getOrgEmail() {
        return this.orgEmail;
    }
    
    public void setOrgEmail(String orgEmail) {
        this.orgEmail = orgEmail;
    }
    public String getOrgWeb() {
        return this.orgWeb;
    }
    
    public void setOrgWeb(String orgWeb) {
        this.orgWeb = orgWeb;
    }
    public String getOrgPhone() {
        return this.orgPhone;
    }
    
    public void setOrgPhone(String orgPhone) {
        this.orgPhone = orgPhone;
    }
    public String getOrgAddress1() {
        return this.orgAddress1;
    }
    
    public void setOrgAddress1(String orgAddress1) {
        this.orgAddress1 = orgAddress1;
    }
    public String getOrgAddress2() {
        return this.orgAddress2;
    }
    
    public void setOrgAddress2(String orgAddress2) {
        this.orgAddress2 = orgAddress2;
    }
    public byte[] getOrgLogo() {
    	String path = FacesContext.getCurrentInstance().getExternalContext().getRealPath("/");
        String fn = path+File.separator+"img/Other298.jpg";
        setFileName(fn);
        setFilePath(fn); 
        File imgFile = new File(fn);
        byte[] imageByte = new byte[(int)imgFile.length()];
        try
        {
            FileInputStream fin = new FileInputStream(imgFile);
            fin.read(imageByte); 
            fin.close();
            this.orgLogo = imageByte;
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
        return this.orgLogo;
    }
    
    public void setOrgLogo(byte[] orgLogo) {
        this.orgLogo = orgLogo;
    }
    public String getOrgRecoveryId() {
        return this.orgRecoveryId;
    }
    
    public void setOrgRecoveryId(String orgRecoveryId) {
        this.orgRecoveryId = orgRecoveryId;
    }
    public String getOrgTanno() {
        return this.orgTanno;
    }
    
    public void setOrgTanno(String orgTanno) {
        this.orgTanno = orgTanno;
    }
    public Integer getOrgRegNoti() {
        return this.orgRegNoti;
    }
    
    public void setOrgRegNoti(Integer orgRegNoti) {
        this.orgRegNoti = orgRegNoti;
    }
    public Byte getOrgStatus() {
        return this.orgStatus;
    }
    
    public void setOrgStatus(Byte orgStatus) {
        this.orgStatus = orgStatus;
    }
    public Date getOrgRegDate() {
        return this.orgRegDate;
    }
    
    public void setOrgRegDate(Date orgRegDate) {
        this.orgRegDate = orgRegDate;
    }
    public String getOrgCountryName() {
        return this.orgCountryName;
    }
    
    public void setOrgCountryName(String orgCountryName) {
        this.orgCountryName = orgCountryName;
    }
    public Set getBankProfiles() {
        return this.bankProfiles;
    }
    
    public void setBankProfiles(Set bankProfiles) {
        this.bankProfiles = bankProfiles;
    }
    public Set getCourseGroupMasters() {
        return this.courseGroupMasters;
    }
    
    public void setCourseGroupMasters(Set courseGroupMasters) {
        this.courseGroupMasters = courseGroupMasters;
    }
    public Set getStudentFeesMasters() {
        return this.studentFeesMasters;
    }
    
    public void setStudentFeesMasters(Set studentFeesMasters) {
        this.studentFeesMasters = studentFeesMasters;
    }
    public Set getTempFinalReports() {
        return this.tempFinalReports;
    }
    
    public void setTempFinalReports(Set tempFinalReports) {
        this.tempFinalReports = tempFinalReports;
    }
    public Set getStudentRegMasters() {
        return this.studentRegMasters;
    }
    
    public void setStudentRegMasters(Set studentRegMasters) {
        this.studentRegMasters = studentRegMasters;
    }
    public Set getChallanMasters() {
        return this.challanMasters;
    }
    
    public void setChallanMasters(Set challanMasters) {
        this.challanMasters = challanMasters;
    }
    public Set getModeOfPayments() {
        return this.modeOfPayments;
    }
    
    public void setModeOfPayments(Set modeOfPayments) {
        this.modeOfPayments = modeOfPayments;
    }
    public Set getMopHeadFieldses() {
        return this.mopHeadFieldses;
    }
    
    public void setMopHeadFieldses(Set mopHeadFieldses) {
        this.mopHeadFieldses = mopHeadFieldses;
    }
    public Set getAdminFeeAdminMasters() {
        return this.adminFeeAdminMasters;
    }
    
    public void setAdminFeeAdminMasters(Set adminFeeAdminMasters) {
        this.adminFeeAdminMasters = adminFeeAdminMasters;
    }
    public Set getExamCodeSetUps() {
        return this.examCodeSetUps;
    }
    
    public void setExamCodeSetUps(Set examCodeSetUps) {
        this.examCodeSetUps = examCodeSetUps;
    }
    public Set getOrgLoginDetailses() {
        return this.orgLoginDetailses;
    }
    
    public void setOrgLoginDetailses(Set orgLoginDetailses) {
        this.orgLoginDetailses = orgLoginDetailses;
    }
    public Set getStudentMasters() {
        return this.studentMasters;
    }
    
    public void setStudentMasters(Set studentMasters) {
        this.studentMasters = studentMasters;
    }
   
       public Set getOrgLogoDetailses() {
        return this.orgLogoDetailses;
    }
    
    public void setOrgLogoDetailses(Set orgLogoDetailses) {
        this.orgLogoDetailses = orgLogoDetailses;
    }
    public Set getOtherFeeHeadMasters() {
        return this.otherFeeHeadMasters;
    }
    
    public void setOtherFeeHeadMasters(Set otherFeeHeadMasters) {
        this.otherFeeHeadMasters = otherFeeHeadMasters;
    }
    public Set getCollegePendingStatuses() {
        return this.collegePendingStatuses;
    }
    
    public void setCollegePendingStatuses(Set collegePendingStatuses) {
        this.collegePendingStatuses = collegePendingStatuses;
    }

    
    

	

	
	
	
	public Set getDegreeTypes() {
		return degreeTypes;
	}


	public void setDegreeTypes(Set degreeTypes) {
		this.degreeTypes = degreeTypes;
	}


	public Set getOrgDepartmentTypes() {
		return orgDepartmentTypes;
	}


	public void setOrgDepartmentTypes(Set orgDepartmentTypes) {
		this.orgDepartmentTypes = orgDepartmentTypes;
	}


		public String getFileName() {
		return fileName;
	}


	public void setFileName(String fileName) {
		String fn;
        fn = fileName.substring(fileName.lastIndexOf("\\")+1,fileName.lastIndexOf(".")); 
		this.fileName = fn;
	}


	
	public String getFilePath() {
		return filePath;
	}


	public Set getBranchMasters() {
		return branchMasters;
	}


	public void setBranchMasters(Set branchMasters) {
		this.branchMasters = branchMasters;
	}


	public void setFilePath(String filePath) {
		String fp;
        fp = filePath.substring(filePath.lastIndexOf(".")+1);
        this.filePath = fp;
	}


	public OrgLoginDetails getOrgLoginDetails() {
		return orgLoginDetails;
	}


	public void setOrgLoginDetails(OrgLoginDetails orgLoginDetails) {
		this.orgLoginDetails = orgLoginDetails;
	}


	public OrgLogoDetails getOrgLogoDetails() {
		return orgLogoDetails;
	}


	public void setOrgLogoDetails(OrgLogoDetails orgLogoDetails) {
		this.orgLogoDetails = orgLogoDetails;
	}


	public IOrgProfileService getiOrgProfileService() {
		return iOrgProfileService;
	}


	public void setiOrgProfileService(IOrgProfileService iOrgProfileService) {
		this.iOrgProfileService = iOrgProfileService;
	}
    
	public void saveProfile()
    {
        try
        { 
            OrgLogoDetails orgld = new OrgLogoDetails(); 
            OrgLoginDetails old = new OrgLoginDetails();
            orgld.setOrgWeb(this.getOrgWeb()); 
            orgld.setOrgLogo(this.getOrgLogo()); 
            orgld.setFileName(this.getFileName());
            orgld.setLogoFormat(this.getFilePath()); 
            old.setAdminId(this.getOrgAdminemailid()); 
            old.setOrgPassword(this.getOrgMasterPassword());
            old.setOrgProfile(this); 
            orgld.setOrgProfile(this);
            //old.setOrgId(this.getOrgId());  
            this.setOrgLogoDetails(orgld); 
            this.setOrgLoginDetails(old); 
            getiOrgProfileService().addNewOrgProfile(this);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }

		
	public void update()
	{
		getiOrgProfileService().updateOrgProfile(new OrgProfileSessionDetails().getOrgProfileSession());  
		
	}

}


