package org.nmeict.smvdu.Beans;
// Generated Apr 11, 2013 7:52:20 PM by Hibernate Tools 3.2.1.GA


import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.component.UIData;
import javax.faces.model.SelectItem;

import org.nmeict.smvdu.Beans.SpringClassFile.IOrgOtherFeeHeadMasterService;
import org.nmeict.smvdu.Beans.SpringClassFile.OrgOtherFeeHeadMasterService;
import org.nmeict.smvdu.HibernateHelper.OrgProfileSessionDetails;

@ManagedBean (name="otherFeeHead")
@RequestScoped
/**
 * OtherFeeHeadMaster generated by hbm2java
 */
public class OtherFeeHeadMaster  implements java.io.Serializable {


     private Integer feeHeadCode;
     private OrgProfile orgProfile;
     private OrgDepartmentType orgDepartmentType;
     private DegreeType degreeType;
     private SemesterMaster semesterMaster;
     private BranchMaster branchMaster;
     private String feeHeadName;
     private double feeHeadValue;
     private String programId;
     private byte payableStatus;
     private Set scholarshipTypes = new HashSet(0);
     private Set studentMasters = new HashSet(0);
     
     
     
     
     
     private Integer semCode;
     private Integer departmentCode;
     private Integer degreeCode;
     private Integer examCode;
     private Integer branchCode;
     private String branchName;
     private String departmentName;
     private String degreeName;
     private String examCodeName;
     private String semesterName;
     private UIData dataGrid;
     private List<OtherFeeHeadMaster> loadAllFeeHead = new ArrayList<OtherFeeHeadMaster>();
     private IOrgOtherFeeHeadMasterService iOrgOtherFeeHeadMasterService = new OrgOtherFeeHeadMasterService();
     private SelectItem[] items;
     
     
     public OtherFeeHeadMaster() {
     }
     public OtherFeeHeadMaster(OrgProfile orgProfile, DegreeType degreeType, String feeHeadName, double feeHeadValue, byte payableStatus) {
         this.orgProfile = orgProfile;
         this.degreeType = degreeType;
         this.feeHeadName = feeHeadName;
         this.feeHeadValue = feeHeadValue;
         this.payableStatus = payableStatus;
     }
     public OtherFeeHeadMaster(OrgProfile orgProfile, OrgDepartmentType orgDepartmentType, DegreeType degreeType, SemesterMaster semesterMaster, BranchMaster branchMaster, String feeHeadName, double feeHeadValue, String programId, byte payableStatus, Set scholarshipTypes, Set studentMasters) {
        this.orgProfile = orgProfile;
        this.orgDepartmentType = orgDepartmentType;
        this.degreeType = degreeType;
        this.semesterMaster = semesterMaster;
        this.branchMaster = branchMaster;
        this.feeHeadName = feeHeadName;
        this.feeHeadValue = feeHeadValue;
        this.programId = programId;
        this.payableStatus = payableStatus;
        this.scholarshipTypes = scholarshipTypes;
        this.studentMasters = studentMasters;
     }
        public Integer getFeeHeadCode() {
        return this.feeHeadCode;
    }
    
    public void setFeeHeadCode(Integer feeHeadCode) {
        this.feeHeadCode = feeHeadCode;
    }
    public OrgProfile getOrgProfile() {
        return this.orgProfile;
    }
    
    public void setOrgProfile(OrgProfile orgProfile) {
        this.orgProfile = orgProfile;
    }
    public OrgDepartmentType getOrgDepartmentType() {
        return this.orgDepartmentType;
    }
    
    public void setOrgDepartmentType(OrgDepartmentType orgDepartmentType) {
        this.orgDepartmentType = orgDepartmentType;
    }
    public DegreeType getDegreeType() {
        return this.degreeType;
    }
    
    public void setDegreeType(DegreeType degreeType) {
        this.degreeType = degreeType;
    }
    public SemesterMaster getSemesterMaster() {
        return this.semesterMaster;
    }
    
    public void setSemesterMaster(SemesterMaster semesterMaster) {
        this.semesterMaster = semesterMaster;
    }
    public BranchMaster getBranchMaster() {
        return this.branchMaster;
    }
    
    public void setBranchMaster(BranchMaster branchMaster) {
        this.branchMaster = branchMaster;
    }
    public String getFeeHeadName() {
        return this.feeHeadName;
    }
    
    public void setFeeHeadName(String feeHeadName) {
        this.feeHeadName = feeHeadName;
    }
    public double getFeeHeadValue() {
        return this.feeHeadValue;
    }
    
    public void setFeeHeadValue(double feeHeadValue) {
        this.feeHeadValue = feeHeadValue;
    }
    public String getProgramId() {
        return this.programId;
    }
    
    
    public void setProgramId(String programId) {
        this.programId = programId;
    }
    public Set getStudentMasters() {
		return studentMasters;
	}
	public void setStudentMasters(Set studentMasters) {
		this.studentMasters = studentMasters;
	}
	public byte getPayableStatus() {
        return this.payableStatus;
    }
    
    public void setPayableStatus(byte payableStatus) {
        this.payableStatus = payableStatus;
    }
    public Set getScholarshipTypes() {
        return this.scholarshipTypes;
    }
    
    public void setScholarshipTypes(Set scholarshipTypes) {
        this.scholarshipTypes = scholarshipTypes;
    }


	public Integer getSemCode() {
		return semCode;
	}


	public void setSemCode(Integer semCode) {
		this.semCode = semCode;
	}


	public Integer getDepartmentCode() {
		return departmentCode;
	}


	public void setDepartmentCode(Integer departmentCode) {
		this.departmentCode = departmentCode;
	}


	public Integer getDegreeCode() {
		return degreeCode;
	}

	

	public Integer getBranchCode() {
		return branchCode;
	}


	public void setBranchCode(Integer branchCode) {
		this.branchCode = branchCode;
	}


	public String getBranchName() {
		return branchName;
	}


	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}


	public void setDegreeCode(Integer degreeCode) {
		this.degreeCode = degreeCode;
	}


	public Integer getExamCode() {
		return examCode;
	}


	public void setExamCode(Integer examCode) {
		this.examCode = examCode;
	}


	public String getDepartmentName() {
		return departmentName;
	}


	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}


	public String getDegreeName() {
		return degreeName;
	}


	public void setDegreeName(String degreeName) {
		this.degreeName = degreeName;
	}


	public String getExamCodeName() {
		return examCodeName;
	}


	public void setExamCodeName(String examCodeName) {
		this.examCodeName = examCodeName;
	}


	
	public UIData getDataGrid() {
		return dataGrid;
	}


	public String getSemesterName() {
		return semesterName;
	}


	
	public void setSemesterName(String semesterName) {
		this.semesterName = semesterName;
	}


	public SelectItem[] getItems() {
		List<OtherFeeHeadMaster> feeCode = getiOrgOtherFeeHeadMasterService().loadOtherFeeHeadCode();
		items = new SelectItem[feeCode.size()];
		for(int i=0;i<feeCode.size();i++)
		{
			OtherFeeHeadMaster dt = feeCode.get(i);
			SelectItem si = new SelectItem(dt.getFeeHeadCode(),dt.getFeeHeadName());
			items[i] = si;
		}
		return items;
	}
	public void setItems(SelectItem[] items) {
		this.items = items;
	}
	public void setDataGrid(UIData dataGrid) {
		this.dataGrid = dataGrid;
	}


	public List<OtherFeeHeadMaster> getLoadAllFeeHead() {
		loadAllFeeHead = getiOrgOtherFeeHeadMasterService().loadOtherFeeHeadCode();
		dataGrid.setValue(loadAllFeeHead);
		return loadAllFeeHead;
	}


	public void setLoadAllFeeHead(List<OtherFeeHeadMaster> loadAllFeeHead) {
		this.loadAllFeeHead = loadAllFeeHead;
	}


	public IOrgOtherFeeHeadMasterService getiOrgOtherFeeHeadMasterService() {
		return iOrgOtherFeeHeadMasterService;
	}


	public void setiOrgOtherFeeHeadMasterService(
			IOrgOtherFeeHeadMasterService iOrgOtherFeeHeadMasterService) {
		this.iOrgOtherFeeHeadMasterService = iOrgOtherFeeHeadMasterService;
	}

    
	public void saveFeeHead()
	{
		OrgProfile op = new OrgProfile();
		OrgDepartmentType odt = new OrgDepartmentType();
		DegreeType dt = new DegreeType();
		SemesterMaster sm = new SemesterMaster();
		BranchMaster bm = new BranchMaster();
		op.setOrgId(new OrgProfileSessionDetails().getOrgProfileSession().getOrgId());
		odt.setOdtSeqNo(this.getDepartmentCode());
		dt.setSeqNo(this.getDegreeCode());
		sm.setSemSeqNo(this.getSemCode());
		bm.setBmSeqNo(this.getBranchCode());
		this.setOrgProfile(op);
		this.setOrgDepartmentType(odt);
		this.setDegreeType(dt);
		this.setSemesterMaster(sm);
		this.setBranchMaster(bm);
		getiOrgOtherFeeHeadMasterService().addNewFeeHeadCode(this);
	}

	public void update()
	{
		List<OtherFeeHeadMaster> otherFeeHead = (ArrayList<OtherFeeHeadMaster>) dataGrid.getValue();
		getiOrgOtherFeeHeadMasterService().updateOtherFeeHeadCode(otherFeeHead);
	}

}


